### ISSUE TITLE
p3ka.com

### ISSUE THREAD

**Issue by Vegasq** [funstream-api/api#10]
Hey, to keep service from subj working, will be great to have some unify API to get whole stream of comments (f.e. /chat/messages/all). As i see from current implementation I will need to request list of streams and generate bunch of requests to api to get something like /chat/history per stream. And resend whole list every 5 seconds. I think it will be pretty useless and generate too much not really needed requests.

Will appreciate it.

**Comment by artaommahe** [comment]
Hi :) you can join and listen [`all`](https://github.com/funstream-api/api/blob/master/chat.md#%D0%9A%D0%B0%D0%BD%D0%B0%D0%BB%D1%8B-%D1%87%D0%B0%D1%82%D0%B0-%D1%82%D0%B5%D0%BA%D1%83%D1%89%D0%B8%D0%B5-%D0%B8-%D0%B7%D0%B0%D0%BF%D0%BB%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5) channel, that will catch all public channels messages(main, stream/*)

**Comment by Vegasq** [comment]
Aha, miss it. Thanks!
