### ISSUE TITLE
не возвращается статус стрима с ск2тв плеера

### ISSUE THREAD

**Issue by AlexMercier** [funstream-api/api#11]
Если стрим идёт через встроенный плеер sc2tv, то метод `/api/player/live` всё равно возвращает статус офлайн, `live:false`

описание метода https://github.com/funstream-api/api/blob/master/player.md

вот мой пример запроса http://funstream.tv/api/player/live?channels=MadSc2tv
даже когда он был онлайн всё равно апи показывало что он оффнут.

**Comment by artaommahe** [comment]
Запустил тестовый стрим, для него корректно выдаёт статус
http://funstream.tv/api/player/live?channels=drow

``` json
[{"id":"drow","live":true,"thumbnail":"Sc2tv","title":"thumbnail","viewers":0}]
```

проблема в регистре - для `channels=madsc2tv` должно возвращать корректно. Передам чтоб поправили, но лучше передавать точное имя канала плеера, а не имя стримера на портале (во встроенном плеере нажать на значок слева сверху - кинет на страницу плеера, оттуда взять имя канала)

**Comment by artaommahe** [comment]
Уточнил - имя канала всегда в нижнем регистре
