### ISSUE TITLE
Работа чата - текст сообщения

### ISSUE THREAD

**Issue by kiridmit** [funstream-api/api#12]
Как зная id сообщения получить его текст?

**Comment by artaommahe** [comment]
@Kiridmit только по id никак - нужен ещё канал. Если знаешь id и channel то можно сделать запрос к https://github.com/funstream-api/api/blob/master/chat.md#История-канала указав в параметрах поиска id сообщения. Сейчас в истории каждого канала хранится только 1к последних сообщений, поэтому старые сообщения не получить никак.
